TOPDIR?=..
SUBDIR=	apply awk basename bc biff cal calendar cmp colrm col column comm compress \
	cut dc dirname du diff3 diff encrypt env expand false file find fmt fold \
	from ftp getconf getent getopt grep head hexdump id indent join jot lam leave \
	lndir logger logname look lorder mkdep mktemp nice nl nohup paste patch \
	pkg-config pr printenv printf readlink renice rev rs sdiff sed shar signify \
	sort spell split stat tail tee telnet tftp time touch tr true tsort tty \
	ul units uname unexpand uniq unvis uudecode uuencode vacation vis wc what \
	which xinstall htpasswd cu newsyslog banner cap_mkdb unifdef whois xargs \
	csplit ctags deroff yes who users
SKIPDIR=ftp cu
include ${.TOPDIR}/mk/bsd.subdir.mk
