name: Ubuntu CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install libedit-dev libssl-dev ncurses-dev zlib1g-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
